DIALECT = 'mysql'
DRIVER = 'pymysql'
USERNAME = 'jtt'
PASSWORD = 'love2you'
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'houserent'
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT, DRIVER, USERNAME, PASSWORD, HOST, PORT, DATABASE)